# Generated by Django 2.2.8 on 2020-01-29 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAsyncImportLog',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('import_type', models.CharField(choices=[(1, 'ADI file from Admin Tool'), (2, 'GL Report from Oracle')], max_length=100)),
                ('import_status', models.CharField(choices=[(1, 'Started'), (2, 'Completed successfully'), (3, 'Failed')], max_length=100)),
                ('import_message', models.CharField(blank=True, max_length=100)),
                ('imported_by', models.CharField(max_length=300)),
                ('import_start', models.DateTimeField(blank=True, editable=False)),
                ('import_end', models.DateTimeField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Import Log',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
