# Generated by Django 2.2.13 on 2020-09-11 13:59
from django.db import migrations

archived_financial_years = [
    2018,
    2019,
]


def set_archived_financial_years(apps, schema_editor):
    financial_year_model = apps.get_model("core", "FinancialYear")
    for year in archived_financial_years:
        obj = financial_year_model.objects.get(pk=year)
        obj.archived = True
        obj.save()



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_data_20200901'),
    ]

    operations = [
        migrations.RunPython(set_archived_financial_years),
    ]
