# Generated by Django 2.2.13 on 2020-09-11 13:59
from django.db import migrations

fields = ["financial_year", "financial_year_display"]


archived_financial_years = [
    [2019, "2019-20"],
    [2018, "2018-19"],
    [2017, "2017-18"],
    [2016, "2016-17"],
]

def set_archived_financial_years(apps, schema_editor):
    financial_year_model = apps.get_model("core", "FinancialYear")
    for year in archived_financial_years:
        d = dict(zip(fields, year))
        year_obj, _ = financial_year_model.objects.get_or_create(**d)
        year_obj.archived = True
        year_obj.save()




class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_data_20200901'),
    ]

    operations = [
        migrations.RunPython(set_archived_financial_years),
    ]
