# Generated by Django 2.2.13 on 2020-08-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200826_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
