# Generated by Django 2.2.13 on 2020-08-13 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chartofaccountDIT', '0002_data_20200522'),
        ('core', '0006_data_20200810'),
        ('costcentre', '0002_auto_20200603_1555'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecast', '0004_auto_20200811_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedFinancialCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('archived', models.DateTimeField(auto_now_add=True)),
                ('archived_analysis1_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ArchivedAnalysis1')),
                ('archived_analysis2_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ArchivedAnalysis2')),
                ('archived_cost_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.HistoricCostCentre')),
                ('archived_natural_account_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ArchivedNaturalCode')),
                ('archived_programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ArchivedProgrammeCode')),
                ('archived_project_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ArchivedProjectCode')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
                ('forecast_expenditure_type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='forecast.ForecastExpenditureType')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleHistoryArchivedFinancialCode',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('archived', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('archived_analysis1_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chartofaccountDIT.ArchivedAnalysis1')),
                ('archived_analysis2_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chartofaccountDIT.ArchivedAnalysis2')),
                ('archived_cost_centre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='costcentre.HistoricCostCentre')),
                ('archived_natural_account_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chartofaccountDIT.ArchivedNaturalCode')),
                ('archived_programme', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chartofaccountDIT.ArchivedProgrammeCode')),
                ('archived_project_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chartofaccountDIT.ArchivedProjectCode')),
                ('financial_year', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.FinancialYear')),
                ('forecast_expenditure_type', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forecast.ForecastExpenditureType')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical archived financial code',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ArchivedForecastData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.BigIntegerField(default=0)),
                ('apr', models.BigIntegerField(default=0)),
                ('may', models.BigIntegerField(default=0)),
                ('jun', models.BigIntegerField(default=0)),
                ('jul', models.BigIntegerField(default=0)),
                ('aug', models.BigIntegerField(default=0)),
                ('sep', models.BigIntegerField(default=0)),
                ('oct', models.BigIntegerField(default=0)),
                ('nov', models.BigIntegerField(default=0)),
                ('dec', models.BigIntegerField(default=0)),
                ('jan', models.BigIntegerField(default=0)),
                ('feb', models.BigIntegerField(default=0)),
                ('mar', models.BigIntegerField(default=0)),
                ('adj1', models.BigIntegerField(default=0)),
                ('adj2', models.BigIntegerField(default=0)),
                ('adj3', models.BigIntegerField(default=0)),
                ('financial_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='previous_years.ArchivedFinancialCode')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
            ],
        ),
        migrations.AddConstraint(
            model_name='archivedfinancialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_analysis1_code__isnull', False), ('archived_analysis2_code__isnull', False), ('archived_project_code__isnull', False)), fields=('archived_programme', 'archived_cost_centre', 'archived_natural_account_code', 'archived_analysis1_code', 'archived_analysis2_code', 'archived_project_code'), name='archived_financial_row_unique_6'),
        ),
        migrations.AddConstraint(
            model_name='archivedfinancialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_analysis1_code__isnull', True), ('archived_analysis2_code__isnull', False), ('archived_project_code__isnull', False)), fields=('archived_programme', 'archived_cost_centre', 'archived_natural_account_code', 'archived_analysis2_code', 'archived_project_code'), name='archived_financial_row_unique_5a'),
        ),
        migrations.AddConstraint(
            model_name='archivedfinancialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_analysis1_code__isnull', False), ('archived_analysis2_code__isnull', True), ('archived_project_code__isnull', False)), fields=('archived_programme', 'archived_cost_centre', 'archived_natural_account_code', 'archived_analysis1_code', 'archived_project_code'), name='archived_financial_row_unique_5b'),
        ),
        migrations.AddConstraint(
            model_name='archivedfinancialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_analysis1_code__isnull', False), ('archived_analysis2_code__isnull', False), ('archived_project_code__isnull', True)), fields=('archived_programme', 'archived_cost_centre', 'archived_natural_account_code', 'archived_analysis1_code', 'archived_analysis2_code'), name='archived_financial_row_unique_5c'),
        ),
        migrations.AddConstraint(
            model_name='archivedfinancialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_analysis1_code__isnull', True), ('archived_analysis2_code__isnull', True), ('archived_project_code__isnull', False)), fields=('archived_programme', 'archived_cost_centre', 'archived_natural_account_code', 'archived_project_code'), name='archived_financial_row_unique_4a'),
        ),
        migrations.AddConstraint(
            model_name='archivedfinancialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_analysis1_code__isnull', False), ('archived_analysis2_code__isnull', True), ('archived_project_code__isnull', True)), fields=('archived_programme', 'archived_cost_centre', 'archived_natural_account_code', 'archived_analysis1_code'), name='archived_financial_row_unique_4b'),
        ),
        migrations.AddConstraint(
            model_name='archivedfinancialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_analysis1_code__isnull', True), ('archived_analysis2_code__isnull', False), ('archived_project_code__isnull', True)), fields=('archived_programme', 'archived_cost_centre', 'archived_natural_account_code', 'archived_analysis2_code'), name='archived_financial_row_unique_4c'),
        ),
        migrations.AddConstraint(
            model_name='archivedfinancialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_analysis1_code__isnull', True), ('archived_analysis2_code__isnull', True), ('archived_project_code__isnull', True)), fields=('archived_programme', 'archived_cost_centre', 'archived_natural_account_code'), name='archived_financial_row_unique_3'),
        ),
    ]
