from openpyxl import load_workbook
from zipfile import BadZipFile

from chartofaccountDIT.models import (
    Analysis1,
    Analysis2,
    NaturalCode,
    ProgrammeCode,
    ProjectCode,
)

from core.import_csv import get_fk, get_fk_from_field
from core.models import FinancialYear

from costcentre.models import CostCentre

from forecast.models import (
    FinancialPeriod,
    MonthlyFigure,
)

from upload_file.utils import set_file_upload_error


CHART_OF_ACCOUNT_COL = "D"
ACTUAL_FIGURE_COL = "F"
NAC_COL = "A"

FIRST_DATA_ROW = 13

MONTH_CELL = "B2"
TITLE_CELL = "B1"
CORRECT_TITLE = "Detail Trial Balance"

# Sample chart of account entry
# '3000-30000-109189-52191003-310940-00000-00000-0000-0000-0000' # noqa
# The following are the index for the
# chart of account after decoded into a list
DIT_INDEX = (
    0
)  # col value must be 3000. If not, the trial balance is for another department # noqa
CC_INDEX = 2
NAC_INDEX = 3
PROGRAMME_INDEX = 4
ANALYSIS1_INDEX = 5
ANALYSIS2_INDEX = 6
PROJECT_INDEX = 7
CHART_ACCOUNT_SEPARATOR = "-"

# TODO Read the value from the database. It should be
# possible for the business to change it.
GENERIC_PROGRAMME_CODE = 310940


class SubTotalFieldDoesNotExistError(Exception):
    pass


class SubTotalFieldNotSpecifiedError(Exception):
    pass


class TrialBalanceError(Exception):
    pass


def get_optional_chart_account_obj(model, chart_of_account_item):
    if int(chart_of_account_item):
        obj, message = get_fk(model, chart_of_account_item)
    else:
        obj = None
        message = ""
    return obj, message


def save_row(chart_of_account, value, period_obj, year_obj):
    """Parse the long strings containing the
    chart of account information. Return errors
    if missing from database."""
    # Sample line:
    # '3000-30000-109189-52191003-310940-00000-00000-0000-0000-0000' # noqa
    chart_account_list = chart_of_account.split(CHART_ACCOUNT_SEPARATOR)
    programme_code = chart_account_list[PROGRAMME_INDEX]
    # Handle lines without programme code
    # TODO put GENERIC_PROGRAMME_CODE in database
    if not int(programme_code):
        if value:
            programme_code = GENERIC_PROGRAMME_CODE
        else:
            return True, ""

    error_message = ""
    nac_obj, message = get_fk(NaturalCode, chart_account_list[NAC_INDEX])
    error_message += message
    if nac_obj:
        #  Check that the NAC is resource or capital
        if not nac_obj.economic_budget_code or \
                nac_obj.economic_budget_code.upper() not in ['RESOURCE', 'CAPITAL']:
            return True, ""
    cc_obj, message = get_fk(CostCentre, chart_account_list[CC_INDEX])
    error_message += message
    programme_obj, message = get_fk(ProgrammeCode, programme_code)
    error_message += message
    analysis1_obj, message = get_optional_chart_account_obj(
        Analysis1,
        chart_account_list[ANALYSIS1_INDEX],
    )
    error_message += message
    analysis2_obj, message = get_optional_chart_account_obj(
        Analysis2,
        chart_account_list[ANALYSIS2_INDEX],
    )
    error_message += message
    project_obj, message = get_optional_chart_account_obj(
        ProjectCode,
        chart_account_list[PROJECT_INDEX],
    )
    error_message += message

    if error_message == "":
        monthly_figure_obj, created = MonthlyFigure.objects.get_or_create(
            financial_year=year_obj,
            programme=programme_obj,
            cost_centre=cc_obj,
            natural_account_code=nac_obj,
            analysis1_code=analysis1_obj,
            analysis2_code=analysis2_obj,
            project_code=project_obj,
            financial_period=period_obj,
        )
        if created:
            # to avoid problems with precision,
            # we store the figures in pence
            monthly_figure_obj.amount = value * 100
        else:
            monthly_figure_obj.amount += value * 100
        monthly_figure_obj.save()
        success = True
    else:
        success = False
    return success, error_message


def check_trial_balance_format(ws, period, year):
    """Check that the file is really the trial
    balance and it is the correct period"""
    if ws.title != "FNDWRR":
        # wrong file
        raise TrialBalanceError(
            "File appears to be incorrect (was it generated by Oracle?)"
        )

    if ws[TITLE_CELL].value != CORRECT_TITLE:
        # wrong file
        raise TrialBalanceError(
            "This file appears to be corrupt (title is incorrect)"
        )

    report_date = ws[MONTH_CELL].value
    if report_date.year != year:
        # wrong date
        raise TrialBalanceError(
            "File is for wrong year"
        )

    if report_date.month != period:
        # wrong date
        raise TrialBalanceError(
            "File is for wrong period"
        )

    return True


def upload_trial_balance_report(file_upload, month_number, year):
    try:
        wb = load_workbook(
            file_upload.document_file,
            read_only=True,
        )
    except BadZipFile as ex:
        set_file_upload_error(
            file_upload,
            "The file is not in the correct format (.xlsx)",
            "BadZipFile (user file is not .xlsx)",
        )
        raise ex

    ws = wb.worksheets[0]

    try:
        check_trial_balance_format(
            ws,
            month_number,
            year,
        )
    except TrialBalanceError as ex:
        wb.close
        set_file_upload_error(
            file_upload,
            str(ex),
            str(ex),
        )
        raise ex

    """TODO Use transactions, so it can 
    rollback if there is an error in 
    the file"""
    year_obj, msg = get_fk(FinancialYear, year)
    period_obj, msg = get_fk_from_field(
        FinancialPeriod,
        "period_calendar_code",
        month_number)
    # Delete the existing actuals.
    # There are multiple lines in the Trial
    # Balance for the same combination of
    # Chart-of-Account, so we need to add
    # the figures when we save them. This
    # means that we need to start with a
    # clean slate.
    MonthlyFigure.objects.filter(
        financial_year=year,
        financial_period=period_obj,
    ).delete()

    for row in range(FIRST_DATA_ROW, ws.max_row):
        if not row % 100:
            print("Processing row {}".format(row))
        chart_of_account = ws["{}{}".format(CHART_OF_ACCOUNT_COL, row)].value
        if chart_of_account:
            actual = ws["{}{}".format(ACTUAL_FIGURE_COL, row)].value
            # No need to save 0 values, because the data has been cleared
            # before starting the upload
            if actual:
                success, error_message = \
                    save_row(chart_of_account, actual, period_obj, year_obj)
                if not success:
                    print('Error at row {}, chart of account {}, message {}'.
                          format(row, chart_of_account, error_message))
        else:
            break
    print("Upload completed")
    period_obj.actual_loaded = True
    period_obj.save()
#     TODO log date and time of upload
