# Generated by Django 3.0.3 on 2021-04-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplehistoryuploadprojectsplitcoefficient',
            name='row_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadprojectsplitcoefficient',
            name='row_number',
            field=models.IntegerField(default=0),
        ),
    ]
