# Generated by Django 2.2.13 on 2020-08-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0003_auto_20200818_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedanalysis1',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedanalysis1_financial_year', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedanalysis2',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedanalysis2_financial_year', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedcommercialcategory',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedcommercialcategory_financial_year', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedexpenditurecategory',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedexpenditurecategory_financial_year', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedfcomapping',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedfcomapping_financial_year', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedinterentity',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedinterentity_financial_year', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivednaturalcode',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivednaturalcode_financial_year', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedprogrammecode',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedprogrammecode_financial_year', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedprojectcode',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedprojectcode_financial_year', to='core.FinancialYear'),
        ),
    ]
