# Generated by Django 2.1.5 on 2019-04-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chartofaccountDIT", "0032_auto_20190403_1354")]

    operations = [
        migrations.AlterModelOptions(
            name="historicfcomapping",
            options={
                "ordering": ["financial_year", "fco_code"],
                "verbose_name": "Historic FCO Mapping",
                "verbose_name_plural": "Historic FCO Mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="historicnaturalcode",
            options={
                "ordering": ["financial_year", "natural_account_code"],
                "verbose_name": "Historic Natural Account Code (NAC)",
                "verbose_name_plural": "Historic Natural Account Codes (NAC)",
            },
        ),
        migrations.AddField(
            model_name="historicanalysis1",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicanalysis2",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historiccommercialcategory",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicexpenditurecategory",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicfcomapping",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicinterentity",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicprogrammecode",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicprojectcode",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
