# Generated by Django 2.2.8 on 2020-01-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicalgroup_historicalpermission_historicaluser'),
        ('chartofaccountDIT', '0051_auto_20191106_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalAnalysis1',
            new_name='ArchiveAnalysis1',
        ),
        migrations.RenameModel(
            old_name='HistoricalAnalysis2',
            new_name='ArchiveAnalysis2',
        ),
        migrations.RenameModel(
            old_name='HistoricalCommercialCategory',
            new_name='ArchiveCommercialCategory',
        ),
        migrations.RenameModel(
            old_name='HistoricalExpenditureCategory',
            new_name='ArchiveExpenditureCategory',
        ),
        migrations.RenameModel(
            old_name='HistoricalFCOMapping',
            new_name='ArchiveFCOMapping',
        ),
        migrations.RenameModel(
            old_name='HistoricalInterEntity',
            new_name='ArchiveInterEntity',
        ),
        migrations.RenameModel(
            old_name='HistoricalNaturalCode',
            new_name='ArchiveNaturalCode',
        ),
        migrations.RenameModel(
            old_name='HistoricalProgrammeCode',
            new_name='ArchiveProgrammeCode',
        ),
        migrations.RenameModel(
            old_name='HistoricalProjectCode',
            new_name='ArchiveProjectCode',
        ),
    ]
