# Generated by Django 2.2.10 on 2020-02-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0053_auto_20200201_1043'),
        ('chartofaccountDIT', '0053_set_budgettype_edit_order'),
    ]

    operations = [
    ]
