# Generated by Django 2.2.10 on 2020-04-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0053_auto_20200403_0828'),
        ('chartofaccountDIT', '0053_auto_20200415_1033'),
    ]

    operations = [
    ]
