# Generated by Django 2.2.10 on 2020-05-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0053_auto_20200403_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedcommercialcategory',
            name='commercial_category',
            field=models.CharField(max_length=255, verbose_name='Commercial Category'),
        ),
        migrations.AlterField(
            model_name='archivedexpenditurecategory',
            name='grouping_description',
            field=models.CharField(max_length=255, verbose_name='Budget Category'),
        ),
        migrations.AlterField(
            model_name='simplehistoryarchivedcommercialcategory',
            name='commercial_category',
            field=models.CharField(max_length=255, verbose_name='Commercial Category'),
        ),
        migrations.AlterField(
            model_name='simplehistoryarchivedexpenditurecategory',
            name='grouping_description',
            field=models.CharField(max_length=255, verbose_name='Budget Category'),
        ),
    ]
