# Generated by Django 2.2.10 on 2020-02-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0054_merge_20200214_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplehistorybudgettype',
            name='budget_type_edit_display_order',
            field=models.IntegerField(default=99),
        ),
    ]
