# Generated by Django 2.2.13 on 2020-08-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_auto_20200615_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecasteditstate',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Lock Forecast'),
        ),
        migrations.AlterField(
            model_name='simplehistoryforecasteditstate',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Lock Forecast'),
        ),
    ]
