# Generated by Django 2.2.10 on 2020-04-02 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_auto_20200330_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlockedforecasteditors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
