# Generated by Django 2.2.10 on 2020-04-02 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecast', '0006_auto_20200402_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForecastEditOpenState',
            new_name='ForecastEditState',
        ),
        migrations.RenameModel(
            old_name='SimpleHistoryForecastEditOpenState',
            new_name='SimpleHistoryForecastEditState',
        ),
        migrations.RenameModel(
            old_name='SimpleHistoryUnlockedForecastEditors',
            new_name='SimpleHistoryUnlockedForecastEditor',
        ),
        migrations.RenameModel(
            old_name='UnlockedForecastEditors',
            new_name='UnlockedForecastEditor',
        ),
        migrations.AlterModelOptions(
            name='simplehistoryforecasteditstate',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical forecast edit state'},
        ),
        migrations.AlterModelOptions(
            name='simplehistoryunlockedforecasteditor',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical unlocked forecast editor'},
        ),
    ]
