# Generated by Django 2.2.10 on 2020-04-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_auto_20200402_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecasteditstate',
            name='lock_date',
            field=models.DateField(blank=True, help_text='If the lock date is set, after this date the system will remain locked until the date is removed', null=True),
        ),
        migrations.AlterField(
            model_name='simplehistoryforecasteditstate',
            name='lock_date',
            field=models.DateField(blank=True, help_text='If the lock date is set, after this date the system will remain locked until the date is removed', null=True),
        ),
    ]
