# Generated by Django 2.2.10 on 2020-04-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_auto_20200402_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecasteditstate',
            options={'default_permissions': ('view', 'change'), 'permissions': [('can_set_edit_lock', 'Can set edit lock'), ('can_edit_whilst_closed', 'Can edit forecasts whilst system is closed'), ('can_edit_whilst_locked', 'Can edit forecasts whilst system is locked')], 'verbose_name_plural': 'Forecast edit state'},
        ),
    ]
