# Generated by Django 2.2.8 on 2020-01-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0050_auto_20200116_1204'),
    ]

    operations = [

        migrations.RunSQL(

            """
                    DROP VIEW if exists forecast_forecast_budget_view ;
                    
                    CREATE VIEW forecast_forecast_budget_view 
                    as
                    SELECT forecast_forecastmonthlyfigure.financial_code_id, "forecast_forecastmonthlyfigure"."financial_year_id" as financial_year,
                    SUM("forecast_budgetmonthlyfigure"."amount") AS "Budget",
                           SUM(CASE WHEN "forecast_financialperiod"."period_short_name" = 'Apr' THEN "forecast_forecastmonthlyfigure"."amount" ELSE NULL END) AS "Apr", 
                           SUM(CASE WHEN "forecast_financialperiod"."period_short_name" = 'Aug' THEN "forecast_forecastmonthlyfigure"."amount" ELSE NULL END) AS "Aug", 
                           SUM(CASE WHEN "forecast_financialperiod"."period_short_name" = 'Dec' THEN "forecast_forecastmonthlyfigure"."amount" ELSE NULL END) AS "Dec", 
                           SUM(CASE WHEN "forecast_financialperiod"."period_short_name" = 'Feb' THEN "forecast_forecastmonthlyfigure"."amount" ELSE NULL END) AS "Feb", 
                           SUM(CASE WHEN "forecast_financialperiod"."period_short_name" = 'Jan' THEN "forecast_forecastmonthlyfigure"."amount" ELSE NULL END) AS "Jan", 
                           SUM(CASE WHEN "forecast_financialperiod"."period_short_name" = 'Jul' THEN "forecast_forecastmonthlyfigure"."amount" ELSE NULL END) AS "Jul", 
                           SUM(CASE WHEN "forecast_financialperiod"."period_short_name" = 'Jun' THEN "forecast_forecastmonthlyfigure"."amount" ELSE NULL END) AS "Jun", 
                           SUM(CASE WHEN "forecast_financialperiod"."period_short_name" = 'Mar' THEN "forecast_forecastmonthlyfigure"."amount" ELSE NULL END) AS "Mar", 
                           SUM(CASE WHEN "forecast_financialperiod"."period_short_name" = 'May' THEN "forecast_forecastmonthlyfigure"."amount" ELSE NULL END) AS "May", 
                           SUM(CASE WHEN "forecast_financialperiod"."period_short_name" = 'Nov' THEN "forecast_forecastmonthlyfigure"."amount" ELSE NULL END) AS "Nov", 
                           SUM(CASE WHEN "forecast_financialperiod"."period_short_name" = 'Oct' THEN "forecast_forecastmonthlyfigure"."amount" ELSE NULL END) AS "Oct", 
                           SUM(CASE WHEN "forecast_financialperiod"."period_short_name" = 'Sep' THEN "forecast_forecastmonthlyfigure"."amount" ELSE NULL END) AS "Sep" 
                    FROM "forecast_forecastmonthlyfigure"
                        INNER JOIN "forecast_financialperiod" ON ("forecast_forecastmonthlyfigure"."financial_period_id" = "forecast_financialperiod"."financial_period_code")
                        LEFT OUTER  JOIN forecast_budgetmonthlyfigure ON 
                        forecast_forecastmonthlyfigure.financial_code_id = "forecast_budgetmonthlyfigure"."financial_code_id"
                        AND forecast_forecastmonthlyfigure.financial_year_id = "forecast_budgetmonthlyfigure"."financial_year_id"
                    WHERE "forecast_forecastmonthlyfigure"."financial_year_id" = 2019 
                    GROUP BY forecast_forecastmonthlyfigure.financial_code_id, "forecast_forecastmonthlyfigure"."financial_year_id"
                    

        """,
        'DROP VIEW "forecast_forecast_budget_view";',

    )

    ]
