# Generated by Django 2.2.8 on 2020-01-16 18:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0051_create_budget_forecast_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastBudgetDataView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('apr', models.BigIntegerField(default=0)),
                ('may', models.BigIntegerField(default=0)),
                ('jun', models.BigIntegerField(default=0)),
                ('jul', models.BigIntegerField(default=0)),
                ('aug', models.BigIntegerField(default=0)),
                ('sep', models.BigIntegerField(default=0)),
                ('oct', models.BigIntegerField(default=0)),
                ('nov', models.BigIntegerField(default=0)),
                ('dec', models.BigIntegerField(default=0)),
                ('jan', models.BigIntegerField(default=0)),
                ('feb', models.BigIntegerField(default=0)),
                ('mar', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'forecast_forecast_budget_view',
                'managed': False,
            },
        ),
        migrations.AlterModelManagers(
            name='budgetmonthlyfigure',
            managers=[
                ('year_budget', django.db.models.manager.Manager()),
            ],
        ),
    ]
