# Generated by Django 2.2.10 on 2020-02-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0060_auto_20200210_1555'),
        ('forecast', '0059_auto_20200201_1043'),
    ]

    operations = [
    ]
