# Generated by Django 2.2.10 on 2020-04-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0049_auto_20200420_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftandhospitality',
            name='days',
        ),
        migrations.RemoveField(
            model_name='giftandhospitality',
            name='months',
        ),
        migrations.RemoveField(
            model_name='giftandhospitality',
            name='years',
        ),
        migrations.RemoveField(
            model_name='simplehistorygiftandhospitality',
            name='days',
        ),
        migrations.RemoveField(
            model_name='simplehistorygiftandhospitality',
            name='months',
        ),
        migrations.RemoveField(
            model_name='simplehistorygiftandhospitality',
            name='years',
        ),
    ]
