# Generated by Django 2.2.10 on 2020-04-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0050_auto_20200420_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftandhospitality',
            name='dates',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dates'),
        ),
        migrations.AddField(
            model_name='giftandhospitality',
            name='months',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Months'),
        ),
        migrations.AddField(
            model_name='giftandhospitality',
            name='years',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Years'),
        ),
        migrations.AddField(
            model_name='simplehistorygiftandhospitality',
            name='dates',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dates'),
        ),
        migrations.AddField(
            model_name='simplehistorygiftandhospitality',
            name='months',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Months'),
        ),
        migrations.AddField(
            model_name='simplehistorygiftandhospitality',
            name='years',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Years'),
        ),
    ]
