# Generated by Django 2.2.10 on 2020-04-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0051_auto_20200420_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftandhospitality',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='giftandhospitality',
            name='months',
        ),
        migrations.RemoveField(
            model_name='giftandhospitality',
            name='years',
        ),
        migrations.RemoveField(
            model_name='simplehistorygiftandhospitality',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='simplehistorygiftandhospitality',
            name='months',
        ),
        migrations.RemoveField(
            model_name='simplehistorygiftandhospitality',
            name='years',
        ),
    ]
