# Generated by Django 2.2.13 on 2020-08-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0002_auto_20200603_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiccostcentre',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costcentre_historiccostcentre_financial_year', to='core.FinancialYear'),
        ),
    ]
