# Generated by Django 2.2.10 on 2020-03-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0031_auto_20200326_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costcentre',
            options={'default_permissions': ('',), 'ordering': ['cost_centre_code'], 'permissions': (('edit_forecast', 'Edit cost centre forecast'),), 'verbose_name': 'Cost Centre', 'verbose_name_plural': 'Cost Centres'},
        ),
    ]
