# Generated by Django 3.0.3 on 2021-04-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_auto_20200820_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='document_type',
            field=models.CharField(choices=[('actuals', 'Actuals'), ('budget', 'Budget'), ('previousyear', 'Previous Year'), ('projectpercentage', 'Project Percentages')], default='actuals', max_length=100),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_location',
            field=models.CharField(choices=[('actuals', 'Actuals'), ('budget', 'Budget'), ('previousyear', 'Previous Year'), ('projectpercentage', 'Project Percentages')], default='S3', max_length=100),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='document_type',
            field=models.CharField(choices=[('actuals', 'Actuals'), ('budget', 'Budget'), ('previousyear', 'Previous Year'), ('projectpercentage', 'Project Percentages')], default='actuals', max_length=100),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='file_location',
            field=models.CharField(choices=[('actuals', 'Actuals'), ('budget', 'Budget'), ('previousyear', 'Previous Year'), ('projectpercentage', 'Project Percentages')], default='S3', max_length=100),
        ),
    ]
