# Generated by Django 2.2.10 on 2020-04-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0003_auto_20200427_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='user_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='user_warning_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='user_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='user_warning_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
