# Generated by Django 2.2.10 on 2020-04-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0004_auto_20200429_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='document_type',
            field=models.CharField(choices=[('actuals', 'Actuals'), ('budget', 'Budget')], default='actuals', max_length=100),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('antivirus', 'Checking for viruses'), ('processed_error', 'Processed. Not uploaded, error(s) found'), ('processed_warning', 'Processed. Uploaded, warning(s) found'), ('processing', 'Processing'), ('parsing', 'Processing after error'), ('processed', 'Processed and uploaded'), ('error', 'Error')], default='unprocessed', max_length=100),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='document_type',
            field=models.CharField(choices=[('actuals', 'Actuals'), ('budget', 'Budget')], default='actuals', max_length=100),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('antivirus', 'Checking for viruses'), ('processed_error', 'Processed. Not uploaded, error(s) found'), ('processed_warning', 'Processed. Uploaded, warning(s) found'), ('processing', 'Processing'), ('parsing', 'Processing after error'), ('processed', 'Processed and uploaded'), ('error', 'Error')], default='unprocessed', max_length=100),
        ),
    ]
