# Generated by Django 2.2.10 on 2020-04-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0005_auto_20200429_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='error_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='warning_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simplehistoryfileupload',
            name='error_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simplehistoryfileupload',
            name='warning_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('antivirus', 'Checking for viruses'), ('processed_error', 'Processed. Not uploaded, error(s) found.'), ('processed_warning', 'Processed. Uploaded, warning(s) found.'), ('processing', 'Processing'), ('parsing', 'Processing after error'), ('processed', 'Processed and uploaded.'), ('error', 'Fatal error.')], default='unprocessed', max_length=100),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('antivirus', 'Checking for viruses'), ('processed_error', 'Processed. Not uploaded, error(s) found.'), ('processed_warning', 'Processed. Uploaded, warning(s) found.'), ('processing', 'Processing'), ('parsing', 'Processing after error'), ('processed', 'Processed and uploaded.'), ('error', 'Fatal error.')], default='unprocessed', max_length=100),
        ),
    ]
