# Generated by Django 2.2.10 on 2020-04-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0006_auto_20200429_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='error_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='warning_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='error_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='warning_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
